/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OrderDetailsImport } from './routes/order-details'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const OrderDetailsRoute = OrderDetailsImport.update({
  path: '/order-details',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/order-details': {
      id: '/order-details'
      path: '/order-details'
      fullPath: '/order-details'
      preLoaderRoute: typeof OrderDetailsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  OrderDetailsRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/order-details"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/order-details": {
      "filePath": "order-details.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
