/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as OrderTrackingImport } from './routes/order/tracking'
import { Route as OrderDetailsImport } from './routes/order/details'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OrderTrackingRoute = OrderTrackingImport.update({
  path: '/order/tracking',
  getParentRoute: () => rootRoute,
} as any)

const OrderDetailsRoute = OrderDetailsImport.update({
  path: '/order/details',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/order/details': {
      id: '/order/details'
      path: '/order/details'
      fullPath: '/order/details'
      preLoaderRoute: typeof OrderDetailsImport
      parentRoute: typeof rootRoute
    }
    '/order/tracking': {
      id: '/order/tracking'
      path: '/order/tracking'
      fullPath: '/order/tracking'
      preLoaderRoute: typeof OrderTrackingImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  OrderDetailsRoute,
  OrderTrackingRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/order/details",
        "/order/tracking"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/order/details": {
      "filePath": "order/details.tsx"
    },
    "/order/tracking": {
      "filePath": "order/tracking.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
